### ISSUE TITLE
Support forwarding to local ports

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#150]
## Problem statement
VGS satellite does not forward to local hosts.
I am running an echo server at port=`3100`, mimtm based VGS satellite running on usual port `9099` locally as well.
```
curl 'http://localhost:3100/post?a=b' -k -x localhost:9099 -H "Content-type: application/json" -d '{"foo": "bar"}'
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException(&#x27;Server connection to (\&#x27;localhost\&#x27;, 3100) failed: Error connecting to &quot;localhost&quot;: [Errno 99] Cannot assign requested address&#x27;)</p>
            </body>
        </html>%                                                                                                                                                 
```
## Advised solution

Its a very common use case, when someone is experimenting with VGS routes locally, more often, they will be running the source and destination servers on the same machine. So this should be allowed. I believe, it should be a small config change in the base mimtm proxy.  

## Testing scenarios
The above pasted curl command should pass.

**Comment by aslepakurov** [comment]
Hey, @devansh-dalal , thanks foryour interest with VGS Satellite!
Yes, indeed, this is a very common case, that we are prioritizing to fix the following week.
Meanwhile as a workaround I suggest you may use [ngrok](https://ngrok.com/) just to surpass `hostname:port` upstream.
I will notify you as soon as we rollout new version that supports this case.

**Comment by rozenbom** [comment]
Hi @devansh-dalal. There are no restrictions with regards to host in VGS Satellite proxy and localhost host should work. Do you run VGS-satellite in a docker container in this particular case? If so I "localhost" in your case is the container's localhost - not the localhost of your host system. If you want local resources to be accessible from a container use host IP address or refer a container from the same network. For example for the following configuration:
```yaml
version: "3.2"
services:
  satellite:
    image: verygood/satellite
    ports:
      - 8089:8089
      - 9098:9098
      - 9099:9099
    volumes:
      - ~/.vgs-satellite:/data
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80


```

The following curl should work perfectly fine:
```bash
curl 'http://httpbin/post?a=b' -k -x localhost:9099 -H "Content-type: application/json" -d '{"foo": "bar"}'
```

**Comment by devansh-dalal** [comment]
Thanks @rozenbom, @aslepakurov  for the quick reply, yes I am actually running docker.

still not able to work with local env.

without proxy: `docker run -p 3100:80 ealen/echo-server`
```
curl 'http://localhost:3100/post?a=b' -k -H "Content-type: application/json" -d '{"foo": "bar"}'          
{"host":{"hostname":"localhost","ip":"::ffff:172.17.0.1","ips":[]},"http":{"method":"POST","baseUrl":"","originalUrl":"/post?a=b","protocol":"http"},"request":{"params":{"0":"/post"},"query":{"a":"b"},"cookies":{},"body":{"foo":"bar"},"headers":{"host":"localhost:3100","user-agent":"curl/7.64.1","accept":"*/*","content-type":"application/json","content-length":"14"}},"environment":{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME":"f51c1bb66365","NODE_VERSION":"12.19.0","YARN_VERSION":"1.22.5","HOME":"/root"}}%   
```

with `docker-compose.yaml`

```
version: '3'
services:
  vgs-satellite:
    image: verygood/satellite
    container_name: vgs-satellite
    ports:
      - 80:80
    volumes:
      - ./src/test/resources/vgs-routes:/data
```

```
vgs-satellite    | [INFO][2021-02-02 02:09:13,817][MainProcess][MainThread] Deleted 0 expired aliases.
vgs-satellite    | [INFO][2021-02-02 02:09:13,853][MainProcess][MainThread] Started proxy(regular) at 9099 port.
vgs-satellite    | [INFO][2021-02-02 02:09:13,890][MainProcess][MainThread] Started proxy(reverse) at 9098 port.
vgs-satellite    | [INFO][2021-02-02 02:09:13,892][MainProcess][MainThread] Web server listening at 8089 port.
```

I am still getting the following error,
```
curl 'http://localhost:3100/post?a=b' -k -x localhost:9099 -H "Content-type: application/json" -d '{"foo": "bar"}'
curl: (7) Failed to connect to localhost port 9099: Connection refused
dd@Devansh-MacBook-Pro stripe-test % curl https://httpbin.org/post -k -x localhost:9099 -H "Content-type: application/json" -d '{"foo": "bar"}'        
curl: (7) Failed to connect to localhost port 9099: Connection refused
```

**Comment by rozenbom** [comment]
> Earlier, I had the ports like this

Those are the right ports (8089, 9098, 9099) that must be exposed if you want to access VGS Satellite from the host environment. 80-port is not used by Statellite.

As I mentioned, **localhost** in your example is not working because you ask Satellite proxy (which is run inside a container) to perform a request to **http://localhost:3100** - **localhost** of this particular container which obviously fails.

Considering your example, here is your compose config:
```yaml
version: "3.2"
services:
  satellite:
    image: verygood/satellite
    ports:
      - 8089:8089
      - 9098:9098
      - 9099:9099
    volumes:
      - ~/.vgs-satellite:/data
  echo:
    image: ealen/echo-server
    ports:
      - 3100:80
```
If you want to perform a request to the echo server **directly** use **localhost**:
```bash
curl 'http://localhost:3100/post?a=b' -k -H "Content-type: application/json" -d '{"foo": "bar"}'
{"host":{"hostname":"localhost","ip":"::ffff:172.25.0.1","ips":[]},"http":{"method":"POST","baseUrl":"","originalUrl":"/post?a=b","protocol":"http"},"request":{"params":{"0":"/post"},"query":{"a":"b"},"cookies":{},"body":{"foo":"bar"},"headers":{"host":"localhost:3100","user-agent":"curl/7.64.1","accept":"*/*","content-type":"application/json","content-length":"14"}},"environment":{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME":"1a80b34ea649","NODE_VERSION":"12.19.0","YARN_VERSION":"1.22.5","HOME":"/root"}}
```

If you want a request to be proxied use the service name from the docker-compose config (**echo** in this case):
```bash
curl 'http://echo/post?a=b' -k -x localhost:9099 -H "Content-type: application/json" -d '{"foo": "bar"}'
{"host":{"hostname":"echo","ip":"::ffff:172.25.0.2","ips":[]},"http":{"method":"POST","baseUrl":"","originalUrl":"/post?a=b","protocol":"http"},"request":{"params":{"0":"/post"},"query":{"a":"b"},"cookies":{},"body":{"foo":"bar"},"headers":{"host":"echo","user-agent":"curl/7.64.1","accept":"*/*","proxy-connection":"Keep-Alive","content-type":"application/json","content-length":"14"}},"environment":{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME":"1a80b34ea649","NODE_VERSION":"12.19.0","YARN_VERSION":"1.22.5","HOME":"/root"}}
```
