### ISSUE TITLE
Regarding errors with route errors from VGS dashboard

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#152]
## Problem statement
I am using VGS satellite for local development/debug on the sandbox environment routes.
This is how I run the satellite docker.

```
version: '3'
services:
  vgs-satellite:
  image: verygood/satellite
  environment:
    SATELLITE_ROUTES_PATH: /data/combined_route.yaml
  ports:
    - 8089:8089
    - 9098:9098
    - 9099:9099
```

But I get the following errors.
```
'Invalid enum value NUM_LENGTH_PRESERVING'
```

seems like its having trouble understanding one of the alias format https://www.verygoodsecurity.com/docs/terminology/nomenclature#alias-formats.
## Advised solution
VGS satellite should have same behaviour as the VGS dashboard.
## Testing scenarios
The attached route yaml should work.

[errors.txt](https://github.com/verygoodsecurity/vgs-satellite/files/5923209/errors.txt)

[combined_route.txt](https://github.com/verygoodsecurity/vgs-satellite/files/5923218/combined_route.txt)
