### ISSUE TITLE
Regarding how to create a route matching 2 or more in VGS satellite

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#158]
## Problem statement
I want to create a route, which is applied on requests for
```
1. localhost:9000
2. httpbin\.org
3. .*\.ngrok\.io
``

How do I configure this in satelite?
In VGS sandox, I was able to put a regexp, but similar expression did not work in satellite.
```
(httpbin\.org|.*\.ngrok\.io)
```

**Comment by rozenbom** [comment]
@devansh-dalal, please provide a route config that works in VGS sandbox and doesn't in VGS Satellite.

**Comment by devansh-dalal** [comment]
Hi

Consider the route,
```
data:
  - attributes:
      created_at: '2021-01-29T05:23:05'
      destination_override_endpoint: '*'
      entries:
        - classifiers: {}
          config:
            condition: OR
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: 736b894f-e754-45d9-a051-3b369eaebfc7
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: PFPT
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.pii
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: OR
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: 5eb6372d-7830-46a8-9e9a-7608d9eb1149
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: PFPT
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.show
          transformer_config_map: null
          type: null
      host_endpoint: (httpbin\.org|postman-echo\.com)
      id: 9e9141dd-aebd-4bdd-8d53-4fa59cdfd2e6
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: rosy-brown-circle
        source: RouteContainer
      updated_at: '2021-01-29T07:55:54'
    id: 9e9141dd-aebd-4bdd-8d53-4fa59cdfd2e6
    type: rule_chain
version: 1
```

It works perfectly in VGS dashboard, but not in satellite. An example of expected output is:

```
dd@Devansh-MacBook-Pro 8-Feb % cat ~/Desktop/VGSVaultCredentials/local/credentials_tnthbonezva.txt 
HTTPS_PROXY_USERNAME="US85kmmS3h7HMopmYxfWmraU"
HTTPS_PROXY_PASSWORD="6c03a631-6c5b-403f-9478-8822d99f3a6f"%                                                                                                            dd@Devansh-MacBook-Pro 8-Feb % curl https://httpbin.org/post -k \                                 
  -x US85kmmS3h7HMopmYxfWmraU:6c03a631-6c5b-403f-9478-8822d99f3a6f@tnthbonezva.sandbox.verygoodproxy.com:8080 \
  -H "Content-type: application/json" \
  -d '{"pii": "424242424242424242"}'
{
  "args": {}, 
  "data": "{\"pii\":\"9914283358055644242\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "29", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.64.1", 
    "Vgs-Request-Id": "72eaf090af907efd320803e969016a57", 
    "X-Amzn-Trace-Id": "Root=1-60215e07-4104cbef584ce90430168723"
  }, 
  "json": {
    "pii": "9914283358055644242"
  }, 
  "origin": "34.206.157.22", 
  "url": "https://httpbin.org/post"
}
dd@Devansh-MacBook-Pro 8-Feb % curl https://postman-echo.com/post -k \      
  -x US85kmmS3h7HMopmYxfWmraU:6c03a631-6c5b-403f-9478-8822d99f3a6f@tnthbonezva.sandbox.verygoodproxy.com:8080 \
  -H "Content-type: application/json" \
  -d '{"pii": "424242424242424242"}'
{"args":{},"data":{"pii":"9914283358055644242"},"files":{},"form":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-60215e2d-5eef6e3b14721de953dbe2d5","content-length":"29","user-agent":"curl/7.64.1","accept":"*/*","content-type":"application/json","vgs-request-id":"233d8b8d45b3a41d3ff28664d564ec19","via":"1.1 e237f7716887"},"json":{"pii":"9914283358055644242"},"url":"https://postman-echo.com/post"}
```
