### ISSUE TITLE
Regarding operation application in the outbound route

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#160]
## Problem statement

I am trying to get an out bound route to reveal the number. But its not applied.
Request: `curl 'http://localhost:9006/post' -k -x localhost:9099 -H "Content-type: application/json" -d '{"number": "9914283735745514242"}'`
Result: 
```{
  "host": {
    "hostname": "localhost",
    "ip": "::ffff:127.0.0.1",
    "ips": [
      
    ]
  },
  "http": {
    "method": "POST",
    "baseUrl": "",
    "originalUrl": "/post",
    "protocol": "http"
  },
  "request": {
    "params": {
      "0": "/post"
    },
    "query": {
      
    },
    "cookies": {
      
    },
    "body": {
      "number": "9914283735745514242"
    },
    "headers": {
      "host": "localhost:9006",
      "user-agent": "curl/7.64.1",
      "accept": "*/*",
      "proxy-connection": "Keep-Alive",
      "content-type": "application/json",
      "content-length": "33"
    }
  },
  "environment": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "c5f7dd2e69b5",
    "PORT": "9006",
    "NODE_VERSION": "12.19.0",
    "YARN_VERSION": "1.22.5",
    "HOME": "/root"
  }
}
```

An echo server is running on `9006` as
```
echo:
    image: ealen/echo-server
    network_mode: "service:vgs-satellite"
    environment:
      PORT: 9006
```

Route.yaml
```
- attributes:
      created_at: '2021-02-07T03:25:09'
      destination_override_endpoint: '*'
      entries:
        - classifiers: {}
          config:
            condition: OR
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
                rules: null
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
                rules: null
          id: 4d74a801-fc88-4fba-92c5-4eee5d0a483e
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: PFPT
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.number
          transformer_config_map: null
      host_endpoint: localhost
      id: c42d4cfa-14cd-49f9-a21c-f474a1ba55c3
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: medium-spring-green-crescent
        source: RouteContainer
      updated_at: '2021-02-07T03:32:04'
    id: c42d4cfa-14cd-49f9-a21c-f474a1ba55c3
    type: rule_chain
```

flow: http://localhost:8089/flows.json
```
[
  {
    "id": "2241603b-6fe7-4851-ab79-177203a9ece4",
    "type": "http",
    "request": {
      "timestamp_start": 1612671504.9953237,
      "timestamp_end": 1612671505.0013068,
      "method": "POST",
      "match_details": {
        "filters": [
          {
            "id": "c05c92f3-d90d-4171-bb72-9ce77109b59f",
            "operation_applied": false
          },
          {
            "id": "690d7e85-4297-43d8-96c1-438007c842ea",
            "operation_applied": false
          }
        ],
        "route_id": "663afd7b-1a24-4437-958b-69ffca992888"
      },
      "http_version": "HTTP/1.1",
      "scheme": "http",
      "port": 9006,
      "content": "{\"number\": \"9914283735745514242\"}",
      "path": "/post",
      "pretty_host": "localhost",
      "host": "localhost",
      "contentLength": 33,
      "headers": [
        [
          "Host",
          "localhost:9006"
        ],
        [
          "User-Agent",
          "curl/7.64.1"
        ],
        [
          "Accept",
          "*/*"
        ],
        [
          "Proxy-Connection",
          "Keep-Alive"
        ],
        [
          "Content-type",
          "application/json"
        ],
        [
          "Content-Length",
          "33"
        ]
      ]
    },
    "error": null,
    "request_raw": {
      "timestamp_start": 1612671504.9953237,
      "timestamp_end": 1612671505.0013068,
      "method": "POST",
      "http_version": "HTTP/1.1",
      "scheme": "http",
      "port": 9006,
      "content": "{\"number\": \"9914283735745514242\"}",
      "path": "/post",
      "pretty_host": "localhost",
      "host": "localhost",
      "contentLength": 33,
      "headers": [
        [
          "Host",
          "localhost:9006"
        ],
        [
          "User-Agent",
          "curl/7.64.1"
        ],
        [
          "Accept",
          "*/*"
        ],
        [
          "Proxy-Connection",
          "Keep-Alive"
        ],
        [
          "Content-type",
          "application/json"
        ],
        [
          "Content-Length",
          "33"
        ]
      ]
    },
    "server_conn": {
      "id": "00291f7d-c23a-446b-a8f1-7bc3c30a9108",
      "timestamp_tcp_setup": 1612671505.0397382,
      "timestamp_tls_setup": null,
      "timestamp_start": 1612671505.0380278,
      "timestamp_end": 1612671505.0953019,
      "sni": null,
      "tls_version": null,
      "tls_established": false,
      "alpn_proto_negotiated": null,
      "source_address": [
        "127.0.0.1",
        36517
      ],
      "ip_address": [
        "127.0.0.1",
        9006
      ],
      "address": [
        "localhost",
        9006
      ]
    },
    "modified": false,
    "mode": "regular",
    "response_raw": {
      "status_code": 200,
      "timestamp_start": 1612671505.072581,
      "timestamp_end": 1612671505.077565,
      "http_version": "HTTP/1.1",
      "reason": "OK",
      "content": "{\"host\":{\"hostname\":\"localhost\",\"ip\":\"::ffff:127.0.0.1\",\"ips\":[]},\"http\":{\"method\":\"POST\",\"baseUrl\":\"\",\"originalUrl\":\"/post\",\"protocol\":\"http\"},\"request\":{\"params\":{\"0\":\"/post\"},\"query\":{},\"cookies\":{},\"body\":{\"number\":\"9914283735745514242\"},\"headers\":{\"host\":\"localhost:9006\",\"user-agent\":\"curl/7.64.1\",\"accept\":\"*/*\",\"proxy-connection\":\"Keep-Alive\",\"content-type\":\"application/json\",\"content-length\":\"33\"}},\"environment\":{\"PATH\":\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"HOSTNAME\":\"c5f7dd2e69b5\",\"PORT\":\"9006\",\"NODE_VERSION\":\"12.19.0\",\"YARN_VERSION\":\"1.22.5\",\"HOME\":\"/root\"}}",
      "contentLength": 599,
      "headers": [
        [
          "Content-Type",
          "application/json; charset=utf-8"
        ],
        [
          "Content-Length",
          "599"
        ],
        [
          "ETag",
          "W/\"257-D6bSG/sPgh1D1KMit+QkI+iWXwM\""
        ],
        [
          "Date",
          "Sun, 07 Feb 2021 04:18:25 GMT"
        ],
        [
          "Connection",
          "keep-alive"
        ],
        [
          "Keep-Alive",
          "timeout=5"
        ]
      ]
    },
    "is_replay": null,
    "client_conn": {
      "id": "d0c20b88-6a4b-42f3-8f4e-90786d505b15",
      "timestamp_tls_setup": null,
      "timestamp_start": 1612671504.9873443,
      "timestamp_end": 1612671505.0974011,
      "sni": null,
      "tls_version": null,
      "tls_established": false,
      "alpn_proto_negotiated": null,
      "cipher_name": null,
      "address": [
        "::ffff:172.24.0.1",
        55446,
        0,
        0
      ]
    },
    "intercepted": false,
    "marked": false,
    "response": {
      "status_code": 200,
      "timestamp_start": 1612671505.072581,
      "timestamp_end": 1612671505.077565,
      "http_version": "HTTP/1.1",
      "reason": "OK",
      "content": "{\"host\":{\"hostname\":\"localhost\",\"ip\":\"::ffff:127.0.0.1\",\"ips\":[]},\"http\":{\"method\":\"POST\",\"baseUrl\":\"\",\"originalUrl\":\"/post\",\"protocol\":\"http\"},\"request\":{\"params\":{\"0\":\"/post\"},\"query\":{},\"cookies\":{},\"body\":{\"number\":\"9914283735745514242\"},\"headers\":{\"host\":\"localhost:9006\",\"user-agent\":\"curl/7.64.1\",\"accept\":\"*/*\",\"proxy-connection\":\"Keep-Alive\",\"content-type\":\"application/json\",\"content-length\":\"33\"}},\"environment\":{\"PATH\":\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"HOSTNAME\":\"c5f7dd2e69b5\",\"PORT\":\"9006\",\"NODE_VERSION\":\"12.19.0\",\"YARN_VERSION\":\"1.22.5\",\"HOME\":\"/root\"}}",
      "contentLength": 599,
      "headers": [
        [
          "Content-Type",
          "application/json; charset=utf-8"
        ],
        [
          "Content-Length",
          "599"
        ],
        [
          "ETag",
          "W/\"257-D6bSG/sPgh1D1KMit+QkI+iWXwM\""
        ],
        [
          "Date",
          "Sun, 07 Feb 2021 04:18:25 GMT"
        ],
        [
          "Connection",
          "keep-alive"
        ],
        [
          "Keep-Alive",
          "timeout=5"
        ]
      ]
    }
  }
]
```

`operation_applied` is always coming out to be false.
