### ISSUE TITLE
Satellite does not support VGS Operations

### ISSUE THREAD

**Issue by gwax** [verygoodsecurity/vgs-satellite#189]
## Problem statement
VGS Satellite does not support the operations specified in https://www.verygoodsecurity.com/docs/operations/overview

## Scenario(s) to reproduce
(describe, how can we reproduce this issue step-by-step)

## Satellite config
(provide satellite config file, by default it is here `~/.vgs-satellite/config.yml`)

## Satellite version
(what version of satellite are you running, for electron app - see `VGS Satellite > About`)

## Log
```
Error: Unable to load routes from file: Invalid routes data: {'data': {1: {'attributes': {'entries': {1: {'operations': {0: {'name': ['Must be one of: github.com/verygoodsecurity/common/compute/LarkyHttp.']}, 1: {'name': ['Must be one of: github.com/verygoodsecurity/common/compute/LarkyHttp.']}, 2: {'name': ['Must be one of: github.com/verygoodsecurity/common/compute/LarkyHttp.']}}}}}}}}
```

## Satellite origin
  - [x] Desktop app (electron)
  - [x] Docker image
  - [ ] Dev

### If you chose `Dev` provide running parameters (how application was started) and console output
(insert how satellite was started and console output)

## Screenshots
(insert screenshots of your issue, where applicable)

## Route configuration
```yaml
data:
  - attributes:
      created_at: "2021-03-30T21:23:01.271034"
      destination_override_endpoint: "http://httpbin"
      entries:
        - classifiers: {}
          config:
            condition: AND
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: 5faee93b-53a6-4e64-abec-538010083217
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_number
            - $.card_cvc
          transformer_config_map: null
          type: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: 948ff71d-ca1b-41e2-b93a-9c22a74b886b
      port: 80
      protocol: http
      source_endpoint: "*"
      tags:
        name: wheat-street
        source: vgs-satellite
    id: 948ff71d-ca1b-41e2-b93a-9c22a74b886b
    type: rule_chain
  - attributes:
      created_at: "2021-03-30T21:23:47.900764"
      destination_override_endpoint: "*"
      entries:
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
                rules: null
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
                rules: null
          id: 6cd0626f-f348-44a1-8193-1b400b29ba9d
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_cvc
            - $.card_number
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
                rules: null
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
                rules: null
          id: 10451e26-648f-4d98-bece-e09d3bc23787
          id_selector: null
          operation: ENRICH
          operations:
            - name: github.com/verygoodsecurity/common/content-type/json/Get
              parameters:
                path: card_number
                var: secretvar
            - name: github.com/verygoodsecurity/common/utils/crypto/rsa/Encrypt
              parameters:
                algorithm: RSA/ECB/NoPadding
                input: ctx.secretvar
                publicKey: >-
                  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDbFOixi7JNveDwRujMmBfqureD+zMkvnzygLX+8XWdmhAozTi3bljvVNQfspI94K7+EpnAaKFf/DxTRFKGzLNwBF80s6JNMF8lMIWE+gtgTvRTX/XBzoyVdFSXikU7F1s/48XXWyYhIJOJI8MWjwDO6ozD934ayChzAfxmMsjK3QIDAQAB
                var: ctx.secretvalue
            - name: github.com/verygoodsecurity/common/content-type/json/Set
              parameters:
                path: card_number
                path_format: string
                value: ctx.secretvalue
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_number
          transformer_config_map: null
      host_endpoint: httpbin
      id: 9ef8e5e8-35b8-4688-8803-3444c7b017ce
      port: 80
      protocol: http
      source_endpoint: "*"
      tags:
        analytic_id: "329653239587724"
        name: green-yellow-children
        source: vgs-satellite
    id: 9ef8e5e8-35b8-4688-8803-3444c7b017ce
    type: rule_chain
version: 1
```
