### ISSUE TITLE
basic examples using docker?

### ISSUE THREAD

**Issue by wi-ski** [verygoodsecurity/vgs-satellite#200]
I LOVE YOU GUYS <3 

Make more money by putting something like this copy-pasta somewhere visible 📈 📈 📈 

### Very Common Example for Local Development/CI

If you have a Redact-and-Reveal configuration, like this: EXAMPLE - its very common to setup a local container for development.

Follow these steps:

### 1. Configure your container with a route from the dashboard (link to export screenshot of yml)

```sh
$  docker run --rm -v $PWD/:/data -p 8089:8089 -p 9098:9098 -p 9099:9099 -e SATELLITE_ROUTES_PATH=/data/file-exported-from-routes-dashboard.yml -e SATELLITE_DEBUG=true verygood/satellite
```

### 2. Confirm it's working

With your local webserver running, do this:
```sh
$  curl 'http://localhost:9098/api/v1/workers/enterprise' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxAc2Vzb2xhYm9yLmNvbSIsImlkIjoxLCJpYXQiOjE2Mjc2ODY4MzR9.Eo13MrboeV1-7KvD4RjXNhi4yQNG3iRcDqedbszR5h4' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw '{"firstName":"Test First","lastName":"Test Last","totallySensitiveValue":"ABC123" }' \
  --compressed
```

#### If you're using a Mac - which is extremely common for things like jobs - you'll want this!

In your exported yml, you'll likely have a line like:

```yml
data:
  - attributes:
      created_at: '2021-04-29T16:56:25'
      destination_override_endpoint: 'http://api.myjob.com' # This needs to change cuz docker is weird on Mac.
```

☝️ Make sure you replace that with:

```yml
data:
  - attributes:
      created_at: '2021-04-29T16:56:25'
      destination_override_endpoint: 'http://host.docker.internal:3000' # This fixes your silly Mac.
```
