### ISSUE TITLE
[Feature Request] Publish Root CA via an api route

### ISSUE THREAD

**Issue by bryanvaz** [verygoodsecurity/vgs-satellite#213]
## Problem statement
In order to allow use VGS with a client side request library in NodeJS without hardcoding a lower security posture (either via using `NODE_EXTRA_CA_CERTS`to allow VGS to be globally trusted, or `NODE_TLS_REJECT_UNAUTHORIZED` to ignore any cert error), we explicitly trust the VGS Root CA only on requests where we interact with VGS.

This is accomplished by feeding the underlying request, usually `https.request()`, the VGS Root CA to trust for the request. An example implementation can be found in the following PR on the Stripe SDK: https://github.com/stripe/stripe-node/pull/1229.

Currently, the only method to obtain the Root CA cert used by VGS Satellite is to mount the Root CA folder as a docker volume, then read the generated cert from the disk. (See below for sample docker-compose mount instructions)

However, in a dockerized CI environment (i.e. Gitlab, CircleCI, Shippable, etc.) services, there is currently no method to mount a docker volume to supporting CI services on job-by-job basis. To get around this, the API should expose a route that publishes the Root CA used by the MITM subsystem, maybe at `GET /root-ca`.

Once published, supporting CI services can just query the endpoint to download the Root CA to trust, the same way in a CI environment, most users use the API to load route configurations before running tests.

## Satellite origin
  - [ ] Desktop app (electron)
  - [x] Docker image
  - [ ] Dev

## Screenshots
(insert screenshots of your issue, where applicable)

**docker-compose.yml** sample
```yml
  vgs:
    ## Used in unit test
    image: verygood/satellite
    platform: linux/x86_64
    environment:
      SATELLITE_DEBUG: 'true'
      SATELLITE_ROUTES_PATH: /data/routes.yml
      SATELLITE_API_PORT: 18089
      SATELLITE_REVERSE_PROXY_PORT: 19098
      SATELLITE_FORWARD_PROXY_PORT: 19099
    ports:
      # <Port exposed> : < VGS Port running inside container>
      - '18089:18089'
      - '19098:19098'
      - '19099:19099'
    expose:
      - '18089'
      - '19098'
      - '19099'
    volumes:
      - type: bind
        source: ./.data/vgs-unit-test/vgs_satellite_data
        target: /data
      - type: bind
        source: ./.data/vgs-unit-test/appdata
        target: /appdata
     # The following mount is required to read the root CA cert
      - type: bind
        source: ./.data/vgs-unit-test/mitmproxy
        target: /root/.mitmproxy
```
